### ISSUE TITLE
inconsistencies between the readme and the changes in the tree data

### ISSUE THREAD

**Issue by janko-js** [MDU-PHL/pango-watch#2]
1) the readme has recombinants, the tree (data.json) doesn't

I've recognized first time seeing that readme has XBG but searching through data.json I don't find it.

More obviously: In commit 36191b4 there's

2022-11-17

    + XBH Recombinant lineage

And the tree remains unchanged, last time changed day before in commit 0524792.

**Comment by janko-js** [comment]
It seems it's "by design":
https://github.com/MDU-PHL/pango-watch/app.py

        if lineage.startswith('X'): # remove recombinants 
            continue

**Comment by janko-js** [comment]
2) In 3edf96d readme lists 

    2022-12-03
         + [BQ.1.1.23](https://cov-lineages.org/lineage.html?lineage=BQ.1.1.23)

but AFAIK BQ.1.1.23 was introduced early November, and since also BQ.1.1.24, BQ.1.1.25, BQ.1.1.26 and the new one is only BQ.1.1.27?

https://github.com/cov-lineages/pango-designation/commits/master/lineage_notes.txt

**Comment by janko-js** [comment]
At least partially solved, recombinants are included in the tree since https://github.com/MDU-PHL/pango-watch/commit/a20648c7821fdb2bb55392243e8581040e6ff304

**Comment by janko-js** [comment]
But trying as an example XBB: 
Per https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt
it is
"XBB	Recombinant lineage of BJ.1 and BA.2.75 with breakpoint in S1, found in USA and Singapore, from issue #1058"

But:

- I see it in the https://mdu-phl.github.io/pango-watch/tree/ with the links to BA.2.10.1 and BM.1.1.1 (?) (as a sibling to BJ.1 ?)

- and I see it in the data.json descending from BJ.1 but with 

      "otherParents": [],

**Comment by Wytamma** [comment]
Hey @janko-js! Sorry I missed this issue (GitHub’s notification system is terrible :/)! That’s so much for point this out. I’ll be away for a few weeks but will fix this once I’m back. Will be happy to merge a PR if you have one :)

**Comment by Wytamma** [comment]
Hi @janko-js I think it's fixed now! Thanks for spotting. Please reopen if i missed something.

**Comment by janko-js** [comment]
Sorry, it still appears wrong.

![pango-watch-bug-2](https://user-images.githubusercontent.com/116484385/222540528-e02401a0-336a-4af7-bce8-b597425b7fce.png)

Three parents? XBB XBB.1 and BA.2.75

But only 2 (XBB.1 and BA.2.75) mentioned in:

https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt

"XBL	Recombinant lineage of XBB.1 with S:F486P and BA.2.75, Malaysia, from issue #1532"

https://github.com/cov-lineages/pango-designation/issues/1532

https://github.com/ktmeaton/ncov-recombinant/issues/219

**Comment by Wytamma** [comment]
Ah! Thanks for following up. I think that’s related to multiple XBB.1 in the key. I think a .unique() will fix it! Will try that now

**Comment by Wytamma** [comment]
Okay I think NOW it is fixed 😅 [abce529](https://github.com/MDU-PHL/pango-watch/commit/abce529d3cd9f903dc42f2c34c2b23927ed0a851)

**Comment by janko-js** [comment]
Still wrong:

  $ pretty-tree.pl | grep XBL
  XBL <XBB+BA.2.75>,

vs.

"XBL Recombinant lineage of XBB.1 with S:F486P and BA.2.75, Malaysia, from issue #1532"

**Comment by Wytamma** [comment]
Ah yes there are a few issues here... 

The tree/data.json file is a hack, it is used to generate a D3js hierarchy. The D3js hierarchy has no concept of nodes with multiple parents (i.e. it is a tree not a graph). I had to hack the layout to add recombinants. So the data.json file wont make sense unless you process the `otherParents` key correctly. I now generate [graph/data.json ](https://github.com/MDU-PHL/pango-watch/blob/main/graph/data.json) which is an actual graph structure and so makes sense for recombinants. 

The multiple parents in the alias_key are the break points i.e. the middle of XBL is BA.2.75.

I can fix the ordering by sorting the parents list so the the recombinant is always first. This may change what it's like now but will at least be consistent from now on.

Thanks for persisting @janko-js

**Comment by Wytamma** [comment]
I think I've fixed it now... but will leave it up to your keen eyes @janko-js (3ab84c8). I've checked and XBL is XBB.1 and BA.2.75. I would use the graph/data.json as the lineages make more sense as a graph when recombinants are included.

**Comment by janko-js** [comment]
I have an impression it's still open, sorry:

Running my script on your json I get:

     XBB <BM.1.1.1+BJ.1>,  

BM.1.1.1?

but lineage_notes.txt:

     XBB	Recombinant lineage of BJ.1 and BA.2.75 with breakpoint in S1, found in USA and Singapore, from issue #1058

i.e. I'd expect BA.2.75 to be there, not BM.1.1.1 ?

**Comment by janko-js** [comment]
I'd also like if you manage to insert the recombinants in the tree always via the longer path (i.e. to the parent which has the most 'dots' in the full name, and internally to track the "number of dots" ("the longest path") even for the recombinants of the recombinants). That would guarantee the ultimate consistency and would also give some clarity about the minimal "naming distance" of every recombinant. I haven't checked if you're already doing that, as the first step is to have the parents which match lineage_notes.txt
I'm sorry for asking that, but I believe it is actually giving more meaning to the "tree". I understand you like graph, but to me the consistent tree can say more about the history of the recognition of the pango subvariants, maybe you'll like the idea too.

**Comment by janko-js** [comment]
How to compare the lineage notes and the tree data.json (recomb-compared.txt is produced):

https://gist.github.com/janko-js/3eb2ea9a7e504a27d24e219d3dafa993

**Comment by Wytamma** [comment]
Awesome 🙏

**Comment by janko-js** [comment]
Thanks! I also think them mentioning two times the same parent is also an issue, and for your program you should keep preserving only the "unique" parents.

**Comment by janko-js** [comment]
It seems, seeing their issue 
https://github.com/cov-lineages/pango-designation/issues/1058
it's indeed BM.1.1.1 so for that specific case it's lineage_notes.txt not updated.

And I think they also should not mention the same parent twice, haven't investigated why that's there.

**Comment by Wytamma** [comment]
I think the double up in the parents are the break points of the recombinant

**Comment by janko-js** [comment]
So it seems the parents match now! Congratulations.

Regarding the ordering I've suggested: I believe it would result in the "tree" with the branches growing "as far as possible" and in a way consistent for the recombinants: the "later" contributing parents would always be from the same level or earlier, and the first would consistently place the variant at least as far away from the "naming root" as the variant with the "most dots" in the longest path allows. I never thought about that solution until I've played with the tree you produce, but I think it has sense. Thanks for all your work!

**Comment by janko-js** [comment]
The comparison using the alias_key.json 

https://gist.github.com/janko-js/6ac001b4a2862d3d4cb8e420a8d5c7cb

Processing with it both alias_key.json and tree/data.json processed with pretty-tree.pl produce at the end the same output (the lines are modified to be split into the relevant "words" which are then made unique, sorted backwards in every line and printed in the same manner):

    XA B.1.177 B.1.1.7 
    XAA BA.2 BA.1 
    XAB BA.2 BA.1 
    XAC BA.2 BA.1 
    XAD BA.2 BA.1 
    XAE BA.2 BA.1 
    XAF BA.2 BA.1 
    XAG BA.2 BA.1 
    XAH BA.2 BA.1 
    XAJ BA.4 BA.2.12.1 
    XAK BA.2 BA.1 
    XAL BA.2 BA.1 
    XAM BA.2.9 BA.1.1 
    XAN BA.5.1 BA.2 
    XAP BA.2 BA.1 
    XAQ BA.2 BA.1 
    XAR BA.2 BA.1 
    XAS BA.5 BA.2 
    XAT BA.2.3.13 BA.1 
    XAU BA.2.9 BA.1.1 
    XAV BA.5 BA.2 
    XAW BA.2 AY.122 
    XAY BA.2 AY.45 
    XAZ BA.5 BA.2.5 
    XB B.1.634 B.1.631 
    XBA BA.2 AY.45 
    XBB BM.1.1.1 BJ.1 
    XBC BA.2 B.1.617.2 
    XBD BF.5 BA.2.75.2 
    XBE BE.4.1 BA.5.2 
    XBF CJ.1 BA.5.2.3 
    XBG BA.5.2 BA.2.76 
    XBH BA.2.75.2 BA.2.3.17 
    XBJ BA.5.2 BA.2.3.20 
    XBK CJ.1 BA.5.2 
    XBL XBB.1 BA.2.75 
    XBM BF.3 BA.2.76 
    XBN XBB.3 BA.2.75 
    XBP BQ.1 BA.2.75 
    XBQ CJ.1 BA.5.2 
    XBR BQ.1 BA.2.75 
    XBS BQ.1 BA.2.75 
    XBT BA.5.2.34 BA.2.75 
    XC B.1.1.7 AY.29 
    XD BA.1 B.1.617.2 
    XE BA.2 BA.1 
    XF BA.1 B.1.617.2 
    XG BA.2 BA.1 
    XH BA.2 BA.1 
    XJ BA.2 BA.1 
    XK BA.2 BA.1 
    XL BA.2 BA.1 
    XM BA.2 BA.1.1 
    XN BA.2 BA.1 
    XP BA.2 BA.1.1 
    XQ BA.2 BA.1.1 
    XR BA.2 BA.1.1 
    XS BA.1.1 B.1.617.2 
    XT BA.2 BA.1 
    XU BA.2 BA.1 
    XV BA.2 BA.1 
    XW BA.2 BA.1 
    XY BA.2 BA.1 
    XZ BA.2 BA.1 

So I'm quite sure the information in both matches now.

**Comment by janko-js** [comment]
I think this issue can be closed. If some new inconsistency occurs, a new issue can be opened, at the moment the tree appears consistent.

**Comment by Wytamma** [comment]
Excellent! Cheers @janko-js
